import { defineField, defineType } from 'sanity'

export default defineType({
    name: 'quoteRequest',
    title: 'Quote Request',
    type: 'document',
    readOnly: true, // Should be generated by API, not edited manually usually
    fields: [
        defineField({ name: 'fullName', type: 'string', title: 'Full Name' }),
        defineField({ name: 'email', type: 'string', title: 'Email' }),
        defineField({ name: 'phone', type: 'string', title: 'Phone' }),
        defineField({ name: 'eventType', type: 'string', title: 'Event Type' }),
        defineField({ name: 'serviceType', type: 'string', title: 'Service Type' }),
        defineField({ name: 'eventDate', type: 'date', title: 'Event Date' }),
        defineField({ name: 'city', type: 'string', title: 'City' }),
        defineField({ name: 'postcode', type: 'string', title: 'Postcode' }),
        defineField({ name: 'guestCount', type: 'number', title: 'Guest Count' }),
        defineField({ name: 'venueType', type: 'string', title: 'Venue Type' }),
        defineField({ name: 'startTime', type: 'string', title: 'Start Time' }),
        defineField({ name: 'endTime', type: 'string', title: 'End Time' }),
        defineField({ name: 'needs', type: 'text', title: 'Additional Needs/Message' }),
        defineField({ name: 'consent', type: 'boolean', title: 'GDPR Consent' }),
        defineField({ name: 'createdAt', type: 'datetime', title: 'Submitted At' }),
    ],
})
