import { defineField, defineType } from 'sanity'

export default defineType({
    name: 'quoteRequest',
    title: 'Demande de Devis',
    type: 'document',
    readOnly: true, // Should be generated by API, not edited manually usually
    fields: [
        defineField({ name: 'fullName', type: 'string', title: 'Nom Complet' }),
        defineField({ name: 'email', type: 'string', title: 'Email' }),
        defineField({ name: 'phone', type: 'string', title: 'Téléphone' }),
        defineField({ name: 'eventType', type: 'string', title: 'Type d\'événement' }),
        defineField({ name: 'serviceType', type: 'string', title: 'Type de Prestation' }),
        defineField({ name: 'eventDate', type: 'date', title: 'Date de l\'événement' }),
        defineField({ name: 'city', type: 'string', title: 'Ville' }),
        defineField({ name: 'postcode', type: 'string', title: 'Code Postal' }),
        defineField({ name: 'guestCount', type: 'number', title: 'Nombre d\'invités' }),
        defineField({ name: 'venueType', type: 'string', title: 'Type de Lieu' }),
        defineField({ name: 'startTime', type: 'string', title: 'Heure de Début' }),
        defineField({ name: 'endTime', type: 'string', title: 'Heure de Fin' }),
        defineField({ name: 'needs', type: 'text', title: 'Besoins / Message' }),
        defineField({ name: 'consent', type: 'boolean', title: 'Consentement RGPD' }),
        defineField({ name: 'createdAt', type: 'datetime', title: 'Date d\'envoi' }),
    ],
})
